apiVersion: apps/v1
kind: Deployment
metadata:
  name: log4shell-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log4shell
  template:
    metadata:
      labels:
        app: log4shell
    spec:
      containers:
      - name: log4shell
        image: log4shell-app:1.0
        ports:
        - containerPort: 8080
        env:
        - name: TOKEN
          value: "eyJhbGciOiJSUzI1NiIsImtpZCI6IkY1bS13V2lPMVNfcGVXM0FRbGwtSTlxeFdSamdkaUdaYmNnWXc2QV9nbEEifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNzE1MTAzMTU1LCJpYXQiOjE3MTUwOTk1NTUsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJkZWZhdWx0Iiwic2VydmljZWFjY291bnQiOnsibmFtZSI6ImFkbWluLXVzZXIiLCJ1aWQiOiJlMDEzYzNmYi00ZjIxLTQzNWQtOGFiYy0xNjQ0Y2E4NmVhMzgifX0sIm5iZiI6MTcxNTA5OTU1NSwic3ViIjoic3lzdGVtOnNlcnZpY2VhY2NvdW50OmRlZmF1bHQ6YWRtaW4tdXNlciJ9.kB5_Z7zWgFiRLpC4Mru7VXoSioDaMlHvawk4nmsmUI8J4g3fpUfqYTsCQ8fkk5VjsFN1b_JfpH5sO0xVbQIfBY1AKAePgDfsGzEam08F6Gk1B-KfX_QkTimpjrwlZ-RWbfmpVHZ9ULRlEXpwU7nOsa1cC7DAhSkkSs92DKBGcuLIX1tDn-Z48qbAmfnrib746-ooCAc31xHG1b8msFx0zAuoWFNhiqEKGPiZq6YK6WBWqs_1nAVo4q4-6DBJmHz9ZNrqJS0gSKmnAyK5-Td_c8YlacgasusyRJASjkaChEUNDTRxEgaUmpWAcHQ63zyUOjfYodsTUTgOy72t6w1PJA"

