apiVersion: v1
kind: Pod
metadata:
  name: rmqbroker
  labels:
    app: rmqbroker
spec:
  containers:
  - name: rmqbroker
    image: apache/rocketmq:4.9.1
    imagePullPolicy: IfNotPresent
    command: ["sh", "mqbroker", "-c", "/opt/rocketmq/conf/broker.conf"]
    env:
    - name: NAMESRV_ADDR
      value: "namesrv:9876"
    - name: MAX_POSSIBLE_HEAP
      value: "200000000"
    ports:
    - containerPort: 10911
    - containerPort: 10909
    volumeMounts:
    - name: broker-conf
      mountPath: /opt/rocketmq/conf/broker.conf
      subPath: broker.conf
  volumes:
  - name: broker-conf
    configMap:
      name: broker-config
