apiVersion: v1
kind: Pod
metadata:
  name: rmqnamesrv
  labels:
    app: rmqnamesrv
spec:
  containers:
  - name: rmqnamesrv
    image: apache/rocketmq:4.9.1
    imagePullPolicy: IfNotPresent
    command: ["sh", "mqnamesrv"]
    ports:
    - containerPort: 9876
