apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring4shell
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring4shell
  template:
    metadata:
      labels:
        app: spring4shell
    spec:
      containers:
      - name: spring4shell
        image: spring4shell
        imagePullPolicy: Never
        ports:
        - containerPort: 8080

