apiVersion: v1
kind: Pod
metadata:
  name: spring4shell
  labels:
    app: spring4shell
spec:
  containers:
  - name: spring4shell
    image: spring4shell
    imagePullPolicy: Never
    ports:
    - containerPort: 8080

