apiVersion: apps/v1
kind: Deployment
metadata:
  name: request-baskets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: request-baskets
  template:
    metadata:
      labels:
        app: request-baskets
    spec:
      hostNetwork: true
      containers:
      - name: request-baskets
        image: darklynx/request-baskets:v1.2.1
        ports:
        - containerPort: 55555
